language: java
jdk:
 - openjdk8
install:
 - mvn clean -B -V
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
 - mvn test -B
script:
 - mvn cobertura:cobertura
jdk:
 - openjdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
